import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/*  AdOpt Tag  */}
        <meta
          name="adopt-website-id"
          content="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        />
        <script
          src="//tag.goadopt.io/injector.js?website_code=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
          className="adopt-injector"
        ></script>
        {/*  End AdOpt Tag  */}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
